### ISSUE TITLE
Parameter config

### ISSUE THREAD

**Issue by im-Kitsch** [geyang/ffn#1]
Hi,

I tried drqv2 and sac_dennis_ffn, but looks the default setting is not rff setting but the standard baseline settings, could you share the parameter settings for rff? It would be very appreciated to reproduce the result.

Best.

**Comment by geyang** [comment]
woops, just saw this. Have you checked out the experiment sweep files defined here: https://github.com/geyang/ffn/tree/main/ffn_analysis/sac_dennis_rff/dmc

Our results should be turn-key reproducible using these sweep files.
